### ISSUE TITLE
Do you think about building a functional package manager?

### ISSUE THREAD

**Issue by flosse** [redox-os/oxide#1]
There is the really interesting package manager [Nix](http://nixos.org/nix/) you might already head of.  I wonder if you have anything in mind for oxide that uses principles of such functional package managers.

**Comment by hauleth** [comment]
Of course. Nix and Guile are main project that we base our design. But we also want to do better than that and improve what they done not so good, i.e. Nix lang is hard (at least for me). We want to make Oxide much easier for newcomers but leave enough space for power users.

We want to use Toml as a configuration language rather than custom syntax (via Nix) with Lua or Ion as a scripting language for builds and management.

Other design principle is to make Oxide distributed. I am thinking about using some kind of P2P as package source (to be precise - BitTorrent with BEP 0019) with cryptographically signed packages to keep everything safe.

**Comment by flosse** [comment]
> We want to make Oxide much easier for newcomers but leave enough space for power users.

that sounds very good!

> We want to use Toml as a configuration language

And can I write custom hooks with it? Is it possible to define expressions that were lazy evaluated and contain more complex procedures?

> Other design principle is to make Oxide distributed. I am thinking about using some kind of P2P as package source

This is a really really good idea! Awesome!

**Comment by hauleth** [comment]
> And can I write custom hooks with it? Is it possible to define expressions that were lazy evaluated and contain more complex procedures?

To be honest I am fan of logicless configuration of package manager/provisioning tool. You only describe state of the machine and then apply it when needed. Logic is only needed in modules (installer, package configuration, etc.). In that situation you should write module script in provided language, in case of Oxide it will be either Ion (most likely) or Lua. So we do not need any logic in Toml files, and we shouldn't need.

**Comment by flosse** [comment]
I see.
I'm really curious about the implemented solution :)
Hopefully I'll be able to contribute once a day some work.
